[package]
name = "huskmap-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Freya desktop map for huskmap."

[dependencies]
huskmap-core.workspace = true
freya = { workspace = true, optional = true }
async-channel = { version = "2", optional = true }
tracing = "0.1"

[features]
default = []
desktop = ["dep:freya", "dep:async-channel"]

[dev-dependencies]
freya-testing = "=0.4.3"
tempfile.workspace = true
